version: '3.8'

services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=dvdrental
      - DB_USER=postgres
      - DB_PASSWORD=password
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=dvdrental
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5555:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./test/data:/db
      - ./test/data/restore.sql:/docker-entrypoint-initdb.d/restore.sql

    restart: unless-stopped

volumes:
  postgres_data:
